
    <h2><?php echo $this->escape($this->subtitle); ?></h2>
            <?php if ($this->usuarioLogueado): ?>

            <div class="menu-opciones">
                   <ul>
                       <li><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/agregar">Agregar noticia</a></li>
                   </ul>
            </div>
            <br/><br/>
        <?php endif; ?>

      <?php
      foreach( $this->noticias as $noticia ) : ?>
        <div id="noticia">
            <div id="noticia-titulo"><?php echo $this->escape($noticia->titulo);?></div>
            <div id="noticia-fecha"><?php echo $this->escape($noticia->fecha);?></div>
            <div id="noticia-contenido"><?php echo $noticia->contenido;?></div>

            <?php if ($this->usuarioLogueado): ?>
                <br>
                <div class="menu-opciones">
                      <ul>
                        <!-- <li><strong>Acciones:</strong></li> -->
                        <li><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/ver/idNoticia/<?php echo $noticia->idNoticia;?>" id="primero">Ver</a></li>
                        <li><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/modificar/idNoticia/<?php echo $noticia->idNoticia;?>">Modificar</a></li>
                        <li><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/eliminar/idNoticia/<?php echo $noticia->idNoticia;?>">Eliminar</a></li>
                    </ul>
                </div>
            <?php endif; ?>
        <div class="div-reset"></div>
        </div>

      <?php endforeach; ?>


    <?php if ($this->usuarioLogueado): ?>
          <div class="menu-opciones">
                   <ul><li><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/agregar">Agregar noticia</a></li></ul>
            </div>
    <?php endif; ?>


