  <h2><?php echo $this->escape($this->subtitle); ?></h2>

  <?php if ($this->usuarioLogueado): ?>
  <table>
    <tr>
      <td><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/modificar/idNoticia/<?php echo $this->noticia->idNoticia;?>">Modificar</a></td>
      <td><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/eliminar/idNoticia/<?php echo $this->noticia->idNoticia;?>">Eliminar</a></td>
    </tr>
  </table>
  <?php endif; ?>

  <div>
    <label for="idNoticia">Id:&nbsp;</label>
    <?php echo $this->escape(trim($this->noticia->idNoticia));?>
  </div>
  <div>
    <label for="titulo">titulo:&nbsp;</label>
    <?php echo $this->escape(trim($this->noticia->titulo));?>
  </div>
  <div>
    <label for="contenido">contenido:&nbsp;</label><br>
    <?php echo $this->noticia->contenido;?>
  </div>

