<div id="footer">
    <a href="<?php echo $this->baseUrl;?>/index.php">Principal</a>  &nbsp;|&nbsp;
    <a href="http://www.surforce.com/blog/">Blog</a>  &nbsp;|&nbsp;
    <a href="http://www.surforce.com/contact.php">Sugerencias</a>  &nbsp;|&nbsp;
    <a href="http://www.surforce.com/terms.php">Términos</a>  &nbsp;|&nbsp;
    <a href="http://www.surforce.com/privacy.php">Privacidad</a>  &nbsp;|&nbsp;
    <strong>Tu Idioma:</strong>&nbsp; <a href="<?php echo $this->baseUrl;?>/set_lang.php?lang=en">English</a>  &nbsp;|&nbsp;
    <a href="<?php echo $this->baseUrl;?>/set_lang.php?lang=es">Español</a><br>
    Copyright - 2008. surforce.com. Todos los derechos reservados.</div>
</div>

  </body>
</html>
