<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">


    <?php if(!empty($this->message)) :?>
        <div id="mensaje">
            <?php echo $this->escape($this->message);?>
        </div>
    <?php endif; ?>

   Chequea tu cuenta, te hemos enviado un mail para que confirmes.


</div>
<?php echo $this->render('footer.phtml'); ?>
