<script src="http://www.google.com/jsapi"></script>

<?php if(isset($this->scriptJs) && array_key_exists('prototype',$this->scriptJs) !== false) :?>
	<script> google.load("prototype", "1.6");</script>
<?php endif; ?>

<?php if(isset($this->scriptJs) && array_key_exists('scriptaculous',$this->scriptJs) !== false ) :?>
	<script>google.load("prototype", "1.6");</script>
	<script>google.load("scriptaculous", "1.8.1");</script>
<?php endif; ?>

<?php if(isset($this->scriptJs) && array_key_exists('jquery',$this->scriptJs) !== false) :?>
	<script>google.load("jquery", "1.2.3");</script>
<?php endif; ?>

<?php if(isset($this->scriptJs) && array_key_exists('mooTools',$this->scriptJs) !== false) :?>
	<script>google.load("mootools", "1.11");</script>
<?php endif; ?>

<?php if(isset($this->scriptJs) && array_key_exists('mooRainbow',$this->scriptJs) !== false) :?>
	
	<script src="<?php echo $this->baseUrl;?>/public/scripts/mooRainbow/mooRainbow.js" type="text/javascript"></script>	
	<script language="JavaScript" type="text/javascript">
		window.addEvent('domready', function() {
			var r = new MooRainbow('myRainbow', {
				imgPath: '<?php echo $this->baseUrl;?>/public/scripts/mooRainbow/images/',
                id: 'rain1',
				'startColor': [58, 142, 246],
				'onChange': function(color) {
					$('myInput').value = color.hex;
				}
			});
		});		

		window.addEvent('domready', function() {
			var r2 = new MooRainbow('myRainbow2', {
				imgPath: '<?php echo $this->baseUrl;?>/public/scripts/mooRainbow/images/',
                id: 'rain2',
				'startColor': [58, 142, 246],
				'onChange': function(color2) {
					$('myInput2').value = color2.hex;
				}
			});
		});
		window.addEvent('domready', function() {
			var r3 = new MooRainbow('myRainbow3', {
				imgPath: '<?php echo $this->baseUrl;?>/public/scripts/mooRainbow/images/',
                id: 'rain3',
				'startColor': [58, 142, 246],
				'onChange': function(color3) {
					$('myInput3').value = color3.hex;
				}
			});
		});
	</script>
<?php endif; ?>  

<?php if(isset($this->scriptJs) && array_key_exists('dojo',$this->scriptJs) !== false) :?>
	<script>google.load("dojo", "1.1.1");</script>
<?php endif; ?>

<?php if(isset($this->scriptJs) && array_key_exists('lighbox',$this->scriptJs) !== false ) :?>
	
	<script src="<?php echo $this->baseUrl;?>/public/scripts/lightbox/lightbox.js" type="text/javascript"></script>	
	<script type="text/javascript">
			window.addEvent('domready',function(){
				Lightbox.init({descriptions: '.lightboxDesc', showControls: true});
			});
		</script>	
<?php endif; ?>


<?php if(isset($this->scriptJs) && array_search('prototypeValidate',$this->scriptJs) !== false) :?>
	<script src="<?php echo $this->baseUrl;?>/public/scripts/prototype/livevalidation_standalone.compressed.js" type="text/javascript"></script>
<?php endif; ?>

 
<?php if(isset($this->scriptJs) && array_search('mooTabs',$this->scriptJs) !== false) :?>
    <script>google.load("mootools", "1.11");</script>
    <script src="<?php echo $this->baseUrl;?>/public/scripts/mootabs/mootabs1.2.js" type="text/javascript"></script>
    <script type="text/javascript" charset="utf-8">
      window.addEvent('domready', init);
      function init() {
      myTabs1 = new mootabs('container', {
            width: '700px',
            height: '250px',
            duration: 1000,
            activateOnLoad: 'first'
      });
      }
</script>
<?php endif; ?>

<script src="<?php echo $this->baseUrl;?>/public/scripts/site.js" type="text/javascript"></script>