<div id="footer">
	<a href="http://contakme.com/index.php">Principal</a>  &nbsp;|&nbsp; <a href="http://blog.contakme.com/">Blog</a>  &nbsp;|&nbsp; <a href="http://contakme.com/contact.php">Sugerencias</a>  &nbsp;|&nbsp; <a href="http://contakme.com/terms.php">Términos</a>  &nbsp;|&nbsp; <a href="http://contakme.com/privacy.php">Privacidad</a>  &nbsp;|&nbsp; <strong>Tu Idioma:</strong>&nbsp; <a href="http://contakme.com/set_lang.php?lang=en">English</a>  &nbsp;|&nbsp; <a href="http://contakme.com/set_lang.php?lang=es">Español</a><br>Copyright © 2007. Contakme.com. Todos los derechos reservados.</div>
</div>

  </body>
</html>
