<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>    
	<?php echo $this->render('_scripts.phtml'); ?>		    
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/site.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/scripts/mooRainbow/mooRainbow.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/scripts/lightbox/lightbox.css" />
  </head>
  <body>
    <div id="contenedor">

	    <div id="cabecera">
	        <h1>SURFORCE-SOCIAL</h1>
	        <?php if( $this->user ) echo "usuario: ".$this->escape($this->user->usuario);?>	        
	       	<ul class="glossymenu">
				<li class="current"><a href="<?php echo $this->baseUrl;?>"><b>Home</b></a></li>				
				<li><a href="<?php echo $this->baseUrl;?>/autenticacion/autenticacion/login/op/sesion"><b>Iniciar Sesión</b></a></li>
				<li><a href="<?php echo $this->baseUrl;?>/registracion/registracion/add/op/registro"><b>Registrarte</b></a></li>
				<li><a href="<?php echo $this->baseUrl;?>/forgotPass/forgotPass/op/lost"><b>Perdí mi clave</b></a></li>
				<li><a href="<?php echo $this->baseUrl;?>/faqs/faqs/op/faqs"><b>FAQs</b></a></li>	
			</ul>
	    </div>
	    

	    