<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->usuario) :?>
  <form action="<?php echo $this->baseUrl ?>/usuarios/usuarios/eliminar" method="post">
    <p>¿Esta seguro que quiere eliminar el usuario '<?php echo $this->escape($this->usuario->usuario); ?>'?</p>
    <div id="boton_formulario">
      <input type="hidden" name="idUsuario" value="<?php echo $this->usuario->idUsuario; ?>" />
      <input type="submit" name="del" value="Si" />
      <input type="submit" name="del" value="No" />
    </div>
  </form>
<?php else: ?>
  <p>No se pudo encontrar el usuario.</p>
<?php endif;?>