
    <? // setup required dojo elements:
       $this->dojo()->enable();
       //->setDjConfigOption('parseOnLoad', true);
    ?>


<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php 
    // Contenedor para tabs
    $this->tabContainer()->captureStart('tab', array(), array('style' => 'width:800px;height:500px;')); 
    
        // Primer tab "Básico"
        $this->contentPane()->captureStart('pane1', array(), array('title' => 'Básico', 'style' => 'padding: 20px;'));
            echo $this->basicoForm;
        echo $this->contentPane()->captureEnd('pane1');
           
        // Segundo tab "Tu Foto"
        $this->contentPane()->captureStart('pane2', array(), array('title' => 'Tu Foto'));
            echo $this->contentPane()->captureEnd('pane2');
        
        // Segundo tab "Password"
           $this->contentPane()->captureStart('pane3', array(), array('title' => 'Password', 'style' => 'padding: 20px;'));
                echo $this->passwordForm;
           echo $this->contentPane()->captureEnd('pane3');

    echo $this->tabContainer()->captureEnd('tab');   
?>